### ISSUE TITLE
Missing a related paper

### ISSUE THREAD

**Issue by alphadl** [yizhen20133868/Awesome-SLU-Survey#1]
[SlotRefine: A Fast Non-Autoregressive Model for Joint Intent Detection and Slot Filling](https://www.aclweb.org/anthology/2020.emnlp-main.152.pdf). In EMNLP 2020. [[code]](https://github.com/moore3930/SlotRefine)

Slot filling and intent detection are two main tasks in spoken language understanding (SLU) system.  In this paper, we propose a novel non-autoregressive model named SlotRefine for joint intent detection and slot filling. Besides, we design a novel two-pass iteration mechanism to handle the uncoordinated slots problem caused by conditional independence of non-autoregressive model. Experiments demonstrate that our model significantly outperforms previous models in slot filling task, while considerably speeding up the decoding (up to ×10.77). In-depth analyses show that 1) pretraining schemes could further enhance our model; 2) two-pass mechanism indeed remedy the uncoordinated slots.

**Comment by alphadl** [comment]
This paper proposed a Fast&Efficient non-autoregressive joint SLU model, achieving the SOTA performance in the SF task.

**Comment by yizhen20133868** [comment]
@alphadl Thanks for your kind mention, we will fix it soon!
