### ISSUE TITLE
请问论文效果和survey的效果为什么不一样呢？

### ISSUE THREAD

**Issue by aprilvkuo** [yizhen20133868/Awesome-SLU-Survey#6]
论文： A Bi-model based RNN Semantic Frame Parsing Model for Intent Detection and Slot Filling

论文上的效果比survey总结的效果要高很多

**Comment by yizhen20133868** [comment]
@aprilvkuo 因为bi-model这篇文章用的数据集预处理和后面的工作不一致，并没有开源，所以我们采用了后面在同一套预处理数据集的报的结果，stack-propagation论文的结果，处理的数据集开源在slot-gate文章中。
